services:
  laravel:
    build:
      context: ./backend
    container_name: laravel
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    networks:
      - app-network

  vue-app:
    container_name: vue-app
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - /frontend:/app
      - /app/node_modules

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
