services:
  vue-app:
    container_name: vue-app
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - frontend:/app
      - /app/node_modules
    
  projeto-sicredi:
    image: mysql:8.0
    container_name: projeto-sicredi
    environment:
      - MYSQL_DATABASE=sicredi-db
      - MYSQL_USER=livia
      - MYSQL_PASSWORD=livia
      - MYSQL_ROOT_PASSWORD=root 
    ports:
      - "3306:3306"
    volumes:
      - projeto-sicredi-data:/var/lib/mysql

volumes:
  projeto-sicredi-data:''
