services:
  projeto-sicredi:
    image: mysql:9.1
    container_name: projeto-sicredi
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - projeto-sicredi-data:/var/lib/mysql

volumes:
  projeto-sicredi-data:
